version: "3"
services:

  api:
      build: .
      restart: always
      ports:
        - 443:443
      environment:
        PORT: 443
      volumes:
        - ./:/go/src/github.com/vijayb8/crypto-api
      networks:
        - cc-be-network

networks:
  cc-be-network: