version: "3"
services:

  api:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        PORT: 8080
        HOST: localhost
      volumes:
        - ./:/go/src/github.com/vijayb8/crypto-api